### PR TITLE
Classical ml upload

### LINKED ISSUE #567: Error when trying to upload a file in the Classical ML tab
**Describe the bug**
There is an error when trying to upload a file in the Classical ML tab. The file is not uploaded.

**To Reproduce**

1. Go to Train
3. Click on Classical ML tab
3. Try to upload a file

### LINKED ISSUE #634: Layer Removal After Train Causes DLP Frontend to Crash And Code Snippet to Change
**Describe the bug**
When removing a layer after training a model in classical-ml, the frontend crashes. When removing a layer after training a model in tabular or img models, the code snippet updates to reflect what layer was removed when it shouldn't.

**To Reproduce**

1. Train a model
2. Remove a layer

**Expected behavior**
The code snippet should display the code based on the layers at the time of training regardless of any additional changes in the layers or parameters.

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: macOS Monterey
- Browser Chrome
- Version 110.0.5481.177

### PR DESCRIPTION
**Pull request by dwu359**
# Classical ml upload

**What user problem are we solving?**
Fixes #567 and fixes #634 
**What solution does this PR provide?**
User can now upload file in classical ml in the same way as tabular, and code snippet now gets the layers directly from the training output.

**Testing Methodology**
Tested on tabular, img-model, and classical ml

**Any other considerations**

### CODE REVIEW

File: frontend/playground-frontend/src/components/ClassicalMLModel/ClassicalMLModel.js [hunk 1]
```diff
@@ -25,29 +25,83 @@ import {
...
   const [email, setEmail] = useState("");
   const [dlpBackendResponse, setDLPBackendResponse] = useState();
   const [beginnerMode, setBeginnerMode] = useState(true);
   const [inputKey, setInputKey] = useState(0);
   const [testSize, setTestSize] = useState(0.2);
   const [problemType, setProblemType] = useState(PROBLEM_TYPES[0]);
+  const [csvDataInput, setCSVDataInput] = useState([]);
+  const [uploadedColumns, setUploadedColumns] = useState([]);
+  const [fileURL, setFileURL] = useState("");
+  const [, setOldCSVDataInput] = useState([]);
```
Comment (karkir0003) [inline frontend/playground-frontend/src/components/ClassicalMLModel/ClassicalMLModel.js:50]: is this a typo? @dwu359

**Review by karkir0003 — COMMENTED** [review]
address nit comments

File: frontend/playground-frontend/src/components/ImageModels/DataCodeSnippet.js [hunk 2]
```diff
@@ -20,6 +19,40 @@ const DataCodeSnippet = (props) => {
...
+ * Depending on layer passed in, this function builds a string with layer's name, and parameters associated to it (if any)
+ * @param {layers} layer
+ * @returns string in form of <layer name>(<parameters>)
+ */
+function layerToString(layer) {
+  let layerToString = layer.object_name + "(";
+
+  if (layer.parameters !== undefined && layer.parameters !== null) {
+    const params = Object.keys(layer.parameters);
+    if (params !== null && params !== undefined && params.length !== 0) {
```
Comment (farisdurrani) [inline frontend/playground-frontend/src/components/ImageModels/DataCodeSnippet.js]: for brevity, recommend rewriting as:
```
if (params?.length !== 0) {
...
```

File: frontend/playground-frontend/src/components/ClassicalMLModel/ClassicalMLModel.js (hunk 1 above)
Comment (dwu359) [reply frontend/playground-frontend/src/components/ClassicalMLModel/ClassicalMLModel.js:50]: No, that's not a typo, that's was the only I could get typescript to stop complaining about an unused variable without using ts-ignore

File: frontend/playground-frontend/src/components/ImageModels/DataCodeSnippet.js (hunk 2 above)
Comment (farisdurrani) [reply frontend/playground-frontend/src/components/ImageModels/DataCodeSnippet.js]: Same as for other similar code

File: frontend/playground-frontend/src/components/ClassicalMLModel/ClassicalMLModel.js (hunk 1 above)
Comment (farisdurrani) [reply frontend/playground-frontend/src/components/ClassicalMLModel/ClassicalMLModel.js:50]: It's anti-pattern but it works, yes. It begs the question why you need that setState in the first place since you can't access the results

Comment (farisdurrani) [reply frontend/playground-frontend/src/components/ClassicalMLModel/ClassicalMLModel.js:50]: But in this case, it's required by the smaller components so we can just leave this here

**Comment by farisdurrani** [comment]
The app broke:
image

**Comment by farisdurrani** [comment]
@karkir0003 none of us are able to connect to the backend because the User is not authenticated. The latest changes to middleware.py broke the code. This is the last middleware.py code that worked: https://github.com/DSGT-DLP/Deep-Learning-Playground/blob/9b0d181dbc7ed8e102cb8db06dc2d7df40083131/backend/middleware.py. 

It seems the middleware-exemption changes you made had some bugs. A simple fix is to revert the code. I tried looking for a better solution to keep your changes but it's going to take too much time when you understand the code better

**Review by farisdurrani — APPROVED** [review]
